### ノードをクリックして、ツリーを伸ばすとき
GET http://localhost:8091/api/nodes/connect/7 HTTP/1.1


### ノードをクリックして、記事を表示させたいとき
GET http://localhost:8091/api/article/info/8 HTTP/1.1


### カードをクリックして、記事を編集したいとき
GET http://localhost:8091/api/node/search/?query=React.js HTTP/1.1


### ユーザーを新規作成したいとき
POST http://localhost:8091/api/user/post HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "uid" : "NLbo4bPckPbLGrsxDb2zoPMr8c83", 
    "name" : "祐生"
}


### 記事を編集したいとき
PUT http://localhost:8091/api/article/edit/1 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer NLbo4bPckPbLGrsxDb2zoPMr8c83

{
    "article": "# Rコンポーネントを開発する際に便利なJavaScriptライブラリです"
}
