version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: Wisdom_Tree_DB
    platform: linux/x86_64
    ports:
      - "3306:3306"
    volumes:
      - ./mysqld_charset.cnf:/etc/mysql/conf.d/mysql_charset.cnf
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wisdomtree
      MYSQL_USER: geek_camp
      MYSQL_PASSWORD: geek_camp_pass
