version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: Wisdom_Tree_DB
    platform: linux/x86_64
    ports:
      - "3306:3306"
    volumes:
      - ./mysqld_charset.cnf:/etc/mysql/conf.d/mysql_charset.cnf
      - ./init/init:/docker-entrypoint-initdb.d
    env_file:
      - ../.env
